task_0:
 video_path: "D:/University/FYP/my_musetalk_version/smaller_talking_man_video.mp4"
 audio_path: "D:/University/FYP/my_musetalk_version/example-woman-voice-trimmed.wav"

# task_1:
#  video_path: "data/video/yongen.mp4"
#  audio_path: "data/audio/eng.wav"
#  bbox_shift: -7 

